FROM node:22-bookworm-slim AS build

WORKDIR /build/server
COPY src/server/package.json src/server/package-lock.json ./
RUN npm ci
COPY src/server ./
RUN npm run build

FROM node:22-bookworm-slim

# Main port
EXPOSE 80/tcp
EXPOSE 80/udp
EXPOSE 8080/tcp
EXPOSE 8080/udp
EXPOSE 843/tcp
EXPOSE 843/udp

ENV NODE_ENV=production
WORKDIR /opt/games/dungeon-blitz-r/src/server

COPY src/server/package.json src/server/package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY --from=build /build/server/dist ./dist
COPY src/server/data ./data
COPY src/client/content/localhost /opt/games/dungeon-blitz-r/src/client/content/localhost
COPY package.json /opt/games/dungeon-blitz-r/package.json

# entrypoint.sh
COPY Container/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    sed -i -e 's/\r$//' /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
