const state={snapshot:null,selectedToken:null};
const sliders=[
  ['damageMultiplier','Hasar','×',0,100,.25],['playerSpeedMultiplier','Oyuncu hızı','×',.25,2.5,.05],
  ['gearDropMultiplier','Gear oranı','×',0,100,.25],['materialDropMultiplier','Material oranı','×',0,100,.25],
  ['goldMultiplier','Gold','×',0,100,.25],['xpMultiplier','XP','×',0,100,.25]
];
const $=id=>document.getElementById(id);const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200)}
async function api(path,options={}){const response=await fetch(`/api/${path}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({error:'Geçersiz sunucu yanıtı'}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function initSliders(){ $('sliders').innerHTML=sliders.map(([id,label,unit,min,max,step])=>`<label class="slider"><div class="slider-head"><span>${label}</span><output id="${id}Out">1${unit}</output></div><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="1"></label>`).join('');sliders.forEach(([id,,unit])=>$(id).addEventListener('input',()=>$(id+'Out').textContent=`${Number($(id).value).toFixed(Number($(id).value)%1?2:0)}${unit}`))}
function render(snapshot){state.snapshot=snapshot;if(state.selectedToken&&!snapshot.players.some(p=>p.token===state.selectedToken))state.selectedToken=null;if(!state.selectedToken&&snapshot.players.length)state.selectedToken=snapshot.players[0].token;
  $('liveDot').className='dot live';$('liveText').textContent='Canlı';$('lastUpdate').textContent=new Date(snapshot.generatedAt).toLocaleTimeString('tr-TR');
  const metricIcons=['<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/>','<path d="m3 6 9-4 9 4-9 4-9-4Z"/><path d="m3 12 9 4 9-4"/>','<path d="M8 12h8M12 8v8"/><circle cx="12" cy="12" r="9"/>','<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'];
  $('metrics').innerHTML=[['Çevrimiçi Oyuncu',snapshot.onlinePlayers,'Aktif oturum'],['Aktif Oda',snapshot.rooms.length,'Canlı örnek'],['Bağlantı',snapshot.connections,'Açık soket'],['Sunucu Süresi',formatUptime(snapshot.uptimeSeconds),'Kesintisiz']].map(([k,v,note],i)=>`<div class="metric"><div class="metric-top"><span>${k}</span><span class="metric-icon"><svg viewBox="0 0 24 24">${metricIcons[i]}</svg></span></div><b>${v}</b><span class="metric-foot"><i></i>${note}</span></div>`).join('');
  $('playerCount').textContent=`${snapshot.players.length} çevrimiçi`;$('navPlayerCount').textContent=snapshot.players.length;$('players').className='player-list'+(snapshot.players.length?'':' empty-state');$('players').innerHTML=snapshot.players.length?snapshot.players.map(p=>`<button class="player ${p.token===state.selectedToken?'selected':''}" data-token="${p.token}"><span class="avatar">${esc(p.name.slice(0,1).toUpperCase()||'?')}</span><span><b>${esc(p.name)}</b><small>${esc(p.level)} · Oda ${p.roomId}</small></span><span class="hp">${p.hp}/${p.maxHp} HP</span></button>`).join(''):'Aktif oyuncu bekleniyor…';
  document.querySelectorAll('.player').forEach(el=>el.onclick=()=>{state.selectedToken=Number(el.dataset.token);render(snapshot)});
  $('roomCount').textContent=`${snapshot.rooms.length} oda`;$('rooms').className='room-list'+(snapshot.rooms.length?'':' empty-state');$('rooms').innerHTML=snapshot.rooms.length?snapshot.rooms.map(r=>`<div class="room"><div class="room-top"><span><b>${esc(r.level)}</b><small>Oda ${r.roomId}</small></span><span class="badge badge-outline">${r.players}P</span></div><div class="room-stats"><span>☠ ${r.hostiles} düşman</span><span>◉ ${r.players} oyuncu</span></div></div>`).join(''):'Aktif oda bekleniyor…';
  const target=snapshot.players.find(p=>p.token===state.selectedToken);$('targetName').textContent=target?target.name:'Oyuncu seçin';$('targetLocation').textContent=target?`${target.level} / ${target.roomId}`:'—';$('targetSummary').innerHTML=target?`<div class="target-avatar">${esc(target.name.slice(0,1).toUpperCase()||'?')}</div><div><strong>${esc(target.name)}</strong><span>${target.hp}/${target.maxHp} HP · ${esc(target.level)} · Oda ${target.roomId}</span></div>`:'<div class="target-avatar">?</div><div><strong>Oyuncu seçilmedi</strong><span>Kontrol etmek için listeden bir oyuncu seçin.</span></div>';
  if(!document.activeElement?.matches('input[type="range"],input[type="checkbox"]'))syncSettings(snapshot.settings);
}
function syncSettings(s){['oneHitEnabled','godModeEnabled','freezeEnemies'].forEach(k=>$(k).checked=Boolean(s[k]));sliders.forEach(([id,,unit])=>{$(id).value=s[id];$(id+'Out').textContent=`${Number(s[id]).toFixed(Number(s[id])%1?2:0)}${unit}`})}
function formatUptime(seconds){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60);return h?`${h}s ${m}d`:`${m} dk`}
async function action(name,extra={}){const target=state.snapshot?.players.find(p=>p.token===state.selectedToken);if(['kill-room','heal-player','kick-player'].includes(name)&&!target){toast('Önce bir oyuncu seçin.',true);return}if(name==='kick-player'&&!confirm(`${target.name} bağlantısı kesilsin mi?`))return;try{const result=await api('action',{method:'POST',body:JSON.stringify({action:name,token:target?.token,roomId:target?.roomId,...extra})});toast(name==='kill-room'?`${result.defeated} düşman öldürüldü.`:'İşlem tamamlandı.')}catch(error){toast(error.message,true)}}
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>action(button.dataset.action));
$('saveSettings').onclick=async()=>{const payload={};['oneHitEnabled','godModeEnabled','freezeEnemies'].forEach(k=>payload[k]=$(k).checked);sliders.forEach(([id])=>payload[id]=Number($(id).value));try{await api('settings',{method:'PATCH',body:JSON.stringify(payload)});toast('Runtime ayarları uygulandı.')}catch(error){toast(error.message,true)}};
$('resetSettings').onclick=async()=>{try{const result=await api('reset',{method:'POST',body:'{}'});syncSettings(result.settings);toast('Ayarlar varsayılana döndü.')}catch(error){toast(error.message,true)}};
$('announceForm').onsubmit=async event=>{event.preventDefault();const message=$('announcement').value.trim();if(!message)return;await action('announce',{message});$('announcement').value=''};
initSliders();const events=new EventSource('/events');events.addEventListener('snapshot',event=>{try{render(JSON.parse(event.data))}catch(error){toast(error.message,true)}});events.onerror=()=>{$('liveDot').className='dot error';$('liveText').textContent='Bağlantı kesildi';$('lastUpdate').textContent='Yeniden deneniyor…'};
$('refreshView').onclick=()=>{if(state.snapshot){render(state.snapshot);toast('Görünüm yenilendi.')}else toast('Canlı sunucu bağlantısı bekleniyor.',true)};
